version: "3.8"
services:
  main:
    build: .
    container_name: aurora-discord-bot
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - justin_mac_address=${justin_mac_address}
      - bingo_mac_address=${bingo_mac_address}
